Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 121
Metrics/MethodLength:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
Metrics/AbcSize:
  Max: 18

Naming/MemoizedInstanceVariableName:
  Enabled: false
Lint/MissingCopEnableDirective:
  Enabled: false
Metrics/ClassLength:
  Max: 150
Style/ClassAndModuleChildren:
  Exclude: 
    - 'test/**/*'
